# NOTE
# kitty_mod is ctrl+shift by default on all platforms

enabled_layouts splits,stack

# -- i3-like window controls

# Auto-position split based on layout
map cmd+enter launch --location=split --cwd=current
# Manually choose split direction
map cmd+[     launch --location=hsplit --cwd=current
map cmd+]     launch --location=vsplit --cwd=current

# Move focus
# map cmd+left  neighboring_window left
# map cmd+right neighboring_window right
# map cmd+up    neighboring_window up
# map cmd+down  neighboring_window down

# Move windows
map alt+shift+left  move_window left
map alt+shift+right move_window right
map alt+shift+up    move_window up
map alt+shift+down  move_window down

# Rotate 90 degrees - allow swapping horizontal/vertical
map alt+shift+L layout_action rotate 90

# -- Tab management

# Uncomment below if using tmux
# remove default shortcuts that clash with custom tmux shortcuts
# map ctrl+shift+left no_op
# map ctrl+shift+right no_op

# Use left+right for tab movement
map ctrl+shift+, no_op
map ctrl+shift+. no_op
map ctrl+shift+left move_tab_backward
map ctrl+shift+right move_tab_forward

# Use alt instead of ctrl for cycling tabs
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab
map alt+tab next_tab
map alt+shift+tab previous_tab

# Use current working directory for new tabs
map kitty_mod+t new_tab_with_cwd
map cmd+t new_tab_with_cwd

# Use cwd for new windows
map kitty_mod+n new_os_window_with_cwd
map cmd+n new_os_window_with_cwd
map cmd+shift+n new_window_with_cwd

# -- Misc

map kitty_mod+r load_config_file
