# Custom tab bar styling
# See: https://github.com/kovidgoyal/kitty/discussions/4447#discussioncomment-3912065

tab_bar_margin_width      5
tab_bar_margin_height     8 0

tab_bar_style             separator
tab_bar_min_tabs          1
tab_separator             ""

tab_title_template        "{fmt.fg._444446}{fmt.bg.default}{fmt.fg._ffffff}{fmt.bg._444444}{(lambda s: s if len(s) < 25 else s[:24] + '…')(title.split()[0].rsplit('/', 1)[-1] or '/')}{fmt.fg._444444}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._656565}{fmt.bg.default}{fmt.fg._ffffff}{fmt.bg._656565}{(lambda s: s if len(s) < 25 else s[:24] + '…')(title.split()[0].rsplit('/', 1)[-1] or '/')}{fmt.fg._656565}{fmt.bg.default} "
